### ISSUE TITLE
Scala-2.13 Support

### ISSUE THREAD

**Issue by abrighton** [jducoeur/jquery-facade#29] opened 2019-08-19 20:21 UTC
Any plans to make a new release for Scala-2.13?

**Comment by jducoeur** [comment] 2019-08-19 20:34
Yeah -- the problem is just that I changed machines since I last cut a release, and I have to figure out how to get things properly set up to do so in my new environment.  It just needs me to be able to scrounge a couple of hours to get all the kinks worked out there...

**Comment by mikla** [comment] 2020-02-25 15:30
@jducoeur I see that everything is ready to be published for Scala 2.13 and Scala.js 1.0.0.
I appreciate if you can find time to do so :)
Thank you!

**Comment by jducoeur** [comment] 2022-06-11 20:45
Long since done, but just realized that I never thought to close the issue.

**Closed as completed by jducoeur** 2022-06-11 20:45 UTC
