### ISSUE TITLE
Ambiguous reference for obj and selector

### ISSUE THREAD

**Issue by ishubham-k** [jducoeur/jquery-facade#10] opened 2016-03-10 14:46 UTC
When I  try to get an element using $("#id") it gives me following error message.
ambiguous reference to overloaded definition,
both method apply in object JQueryStatic of type (obj: scala.scalajs.js.Object)org.querki.jquery.JQuery
and  method apply in object JQueryStatic of type (selector: org.querki.jquery.ElementDesc)org.querki.jquery.JQuery
match argument types (String)

**Comment by jducoeur** [comment] 2016-03-10 14:53
That's odd -- if that were a legitimate error, I should be hitting it myself all over the place.  Is it possible for you to share the file?  The weirdness here is that I don't expect "#id" to match js.Object -- I'm not sure why that's happening...

**Comment by ishubham-k** [comment] 2016-03-10 15:02
So I am trying to do $("#loginLoader").removeClass("hidden"). I am using "org.querki" %%% "jquery-facade" % "1.0-RC1", as my dependency and importing import org.querki.jquery._

**Comment by ishubham-k** [comment] 2016-03-10 15:05
Also previously I was using "org.querki" %%% "jquery-facade" % "0.10" and it use to work then.

**Comment by jducoeur** [comment] 2016-03-10 16:21
Actually, what I care about most is what _other_ imports you have in the file.  I mean, I'm doing approximately the same thing as you in a number of places -- choosing one at random:

```
$("html, body").scrollTop(($(document).height()-$(window).height()).toInt);
```

So the question is, what's different about your file that is causing $("...") to get confused?  In particular, why does the Scala compiler think it's appropriate to interpret a String literal as a js.Object, which is what your error message indicates?  I'm concerned that you've got some implicit somewhere that's doing something weird...

**Comment by jducoeur** [comment] 2016-03-10 16:26
Just to illustrate that the `#id` form isn't relevant, I also have:

```
$("#_pageStyles").each({ (e:dom.Element) => ...
```

The issue appears to be that something's making the String be seen in this location as a js.Object.  I _think_ that implies a misbehaving implicit, but without seeing the code I can't be certain.

Actually, here's a test to see if my theory is correct.  Right before the offending line, write:

```
val dummy:js.Object = "hello"
```

That's _should_ give a compiler error, saying that "hello" can't be assigned to js.Object.  Does it?

**Comment by ishubham-k** [comment] 2016-03-11 03:04
Thanks for the reply. I will check it once again, try out your suggestions and get back to you today.

**Comment by ishubham-k** [comment] 2016-03-14 23:41
Hi sorry for the late reply, got a little engaged with other stuff. I have tried what you have suggested like  
`val  availableToDate : js.Object = "#availableToDate"` and it doesn't throw an error. So for me it works for now as I have assigned places where I used it to js,Object. But for some reason $() expects js.Object than actual string. You can take a look at the code [here](https://github.com/LivelyGig/ProductWebUI/blob/master/client/src/main/scala/l/client/modules/Searches.scala#L61-L72) and [here](https://github.com/LivelyGig/ProductWebUI/blob/master/client/src/main/scala/l/client/modalpopups/AgentLogin.scala#L76-L77)

**Comment by jducoeur** [comment] 2016-03-15 13:49
Well, the heart of the issue is that you have some other implicit in scope (probably unrelated to jquery-facade) that is casting String to js.Object -- the above test proves that.  If you're using an IDE, you might be able to track down where that's coming from.  (There are enough imports in those files that I can't easily make a guess.)

But so long as that's the case, you're going to have to work around this: the problem isn't with the facade itself, but with this other implicit, which is doing something I personally consider pretty unwise.  (It's not even technically correct -- String and Object are different primitives at the JS level, IIRC -- although you can often get away with it.)

So I'm going to close this Issue, unless we come up with some reason to reopen it...

**Closed as completed by jducoeur** 2016-03-15 13:49 UTC

**Comment by ishubham-k** [comment] 2016-03-16 02:23
Sure thanks.
